version: '3.7'

services:
  app:
    image: ${DOCKER_BASE}-app:latest
    ports:
      - ${PORT}:${PORT}
    command: ["develop"]
    environment:
      - PORT
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - SECRET
      - NODE_ENV
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - development

networks:
  development:
    external: true

volumes:
  node_modules:
