version: '3.7'

services:
  app:
    image: ${DOCKER_BASE}/app:latest
    environment:
      - SERVER_PORT=9000
      - NODE_ENV
      - SERVER_ROOT=/app/public
      - SERVER_ASSETS=/app/public/static
    networks:
      - default

networks:
  default:
    name: ${NETWORK}
    external: true

volumes:
  node_modules:
