version: '3.7'

services:
  app:
    image: ${DOCKER_BASE}-app:latest
    environment:
      - NODE_ENV
    networks:
      - haproxy-controller_haproxy-controller

networks:
  haproxy-controller_haproxy-controller:
    external: true

volumes:
  node_modules:
