version: '3.7'

services:
  app:
    image: ${DOCKER_BASE}-app:latest
    ports:
      - ${PORT}:${PORT}
    command: ["develop"]
    environment:
      - PORT
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - SECRET
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    # depends_on:
    #   - db

  # db:
  #   image: postgres
  #   restart: always
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_USER
  #     - POSTGRES_PASSWORD
  #     - POSTGRES_DB
  #     - PGDATA=/var/lib/postgresql/data/pgdata
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

volumes:
  node_modules:
    # name: ${PROJECT}_node_modules
  # app:
  #   image: 'benbergstein/bread:latest'
  #   ports:
  #     - "9000:3000"
  #   volumes:
  #     - ./:/app
